package com.quicklauncher.app

import android.content.Context
import android.graphics.Typeface

/** Font Awesome glyph table (same icon set as the HTML prototype). */
data class Glyph(val brands: Boolean, val cp: Int) {
    val text: String get() = String(Character.toChars(cp))
}

private fun S(cp: Int) = Glyph(false, cp)
private fun B(cp: Int) = Glyph(true, cp)

object Fa {
    private var solid: Typeface? = null
    private var brands: Typeface? = null

    fun typeface(ctx: Context, brandsFont: Boolean): Typeface {
        if (brandsFont) {
            return brands ?: Typeface.createFromAsset(ctx.applicationContext.assets, "fa-brands-400.ttf").also { brands = it }
        }
        return solid ?: Typeface.createFromAsset(ctx.applicationContext.assets, "fa-solid-900.ttf").also { solid = it }
    }

    fun glyph(cls: String): Glyph? = MAP[cls]

    /** Icons offered by the preset picker. */
    val PRESETS: List<String> by lazy { MAP.keys.toList() }

    private val MAP: Map<String, Glyph> = mapOf(
    "fa-solid fa-camera" to S(0xf030),
    "fa-solid fa-hard-drive" to S(0xf0a0),
    "fa-solid fa-camera-rotate" to S(0xe0d8),
    "fa-solid fa-video" to S(0xf03d),
    "fa-solid fa-images" to S(0xf302),
    "fa-solid fa-heart" to S(0xf004),
    "fa-solid fa-magnifying-glass" to S(0xf002),
    "fa-solid fa-location-dot" to S(0xf3c5),
    "fa-solid fa-house" to S(0xf015),
    "fa-solid fa-briefcase" to S(0xf0b1),
    "fa-solid fa-music" to S(0xf001),
    "fa-solid fa-gear" to S(0xf013),
    "fa-solid fa-battery-half" to S(0xf242),
    "fa-solid fa-wifi" to S(0xf1eb),
    "fa-brands fa-chrome" to B(0xf268),
    "fa-solid fa-plus" to S(0x2b),
    "fa-solid fa-user-secret" to S(0xf21b),
    "fa-brands fa-youtube" to B(0xf167),
    "fa-solid fa-rectangle-list" to S(0xf022),
    "fa-solid fa-calculator" to S(0xf1ec),
    "fa-solid fa-clock" to S(0xf017),
    "fa-solid fa-bell" to S(0xf0f3),
    "fa-solid fa-stopwatch" to S(0xf2f2),
    "fa-solid fa-note-sticky" to S(0xf249),
    "fa-solid fa-pen-to-square" to S(0xf044),
    "fa-solid fa-list-check" to S(0xf0ae),
    "fa-brands fa-whatsapp" to B(0xf232),
    "fa-solid fa-message" to S(0xf27a),
    "fa-solid fa-user" to S(0xf007),
    "fa-solid fa-address-book" to S(0xf2b9),
    "fa-solid fa-users" to S(0xf0c0),
    "fa-brands fa-telegram" to B(0xf2c6),
    "fa-solid fa-bookmark" to S(0xf02e),
    "fa-solid fa-user-group" to S(0xf500),
    "fa-solid fa-folder-open" to S(0xf07c),
    "fa-solid fa-download" to S(0xf019),
    "fa-solid fa-comment-dots" to S(0xf4ad),
    "fa-solid fa-bag-shopping" to S(0xf290),
    "fa-solid fa-cubes" to S(0xf1b3),
    "fa-solid fa-cube" to S(0xf1b2),
    "fa-solid fa-phone" to S(0xf095),
    "fa-solid fa-phone-flip" to S(0xf879),
    "fa-solid fa-comment-sms" to S(0xf7cd),
    "fa-solid fa-envelope" to S(0xf0e0),
    "fa-solid fa-globe" to S(0xf0ac),
    "fa-solid fa-terminal" to S(0xf120),
    "fa-solid fa-file-lines" to S(0xf15c),
    "fa-solid fa-sliders" to S(0xf1de),
    "fa-solid fa-folder" to S(0xf07b),
    "fa-solid fa-file-pdf" to S(0xf1c1),
    "fa-solid fa-film" to S(0xf008),
    "fa-solid fa-image" to S(0xf03e),
    "fa-solid fa-moon" to S(0xf186),
    "fa-solid fa-power-off" to S(0xf011),
    "fa-solid fa-lock" to S(0xf023),
    "fa-solid fa-expand" to S(0xf065),
    "fa-solid fa-clone" to S(0xf24d),
    "fa-solid fa-chevron-left" to S(0xf053),
    "fa-solid fa-volume-high" to S(0xf028),
    "fa-solid fa-volume-xmark" to S(0xf6a9),
    "fa-solid fa-sun" to S(0xf185),
    "fa-brands fa-bluetooth-b" to B(0xf294),
    "fa-solid fa-lightbulb" to S(0xf0eb),
    "fa-solid fa-plane" to S(0xf072),
    "fa-solid fa-rotate" to S(0xf2f1),
    "fa-solid fa-bell-slash" to S(0xf1f6),
    "fa-solid fa-tower-broadcast" to S(0xf519),
    "fa-solid fa-shield-halved" to S(0xf3ed),
    "fa-brands fa-github" to B(0xf09b),
    "fa-solid fa-xmark" to S(0xf00d),
    "fa-solid fa-chevron-up" to S(0xf077),
    "fa-solid fa-chevron-down" to S(0xf078),
    "fa-solid fa-check" to S(0xf00c),
    "fa-solid fa-trash" to S(0xf1f8),
    "fa-solid fa-arrow-up" to S(0xf062),
    "fa-solid fa-arrow-down" to S(0xf063),
    "fa-brands fa-android" to B(0xf17b),
    "fa-solid fa-code" to S(0xf121),
    "fa-solid fa-file-excel" to S(0xf1c3),
    "fa-solid fa-turn-up" to S(0xf3bf),
    "fa-solid fa-layer-group" to S(0xf5fd),
    "fa-solid fa-crop" to S(0xf125),
    "fa-solid fa-signal" to S(0xf012),
    "fa-solid fa-pen" to S(0xf304),
    "fa-solid fa-circle" to S(0xf111),
    "fa-solid fa-arrow-turn-down" to S(0xf149),
    "fa-solid fa-bolt" to S(0xf0e7),
    "fa-solid fa-toggle-on" to S(0xf205),
    "fa-solid fa-database" to S(0xf1c0),
    "fa-solid fa-pen-ruler" to S(0xf5ae),
    "fa-solid fa-file-export" to S(0xf56e),
    "fa-solid fa-file-import" to S(0xf56f),
    "fa-solid fa-star" to S(0xf005),
    "fa-solid fa-gamepad" to S(0xf11b),
    "fa-solid fa-book" to S(0xf02d),
    "fa-solid fa-cart-shopping" to S(0xf07a),
    "fa-solid fa-credit-card" to S(0xf09d),
    "fa-solid fa-calendar" to S(0xf133),
    "fa-solid fa-car" to S(0xf1b9),
    "fa-solid fa-bicycle" to S(0xf206),
    "fa-solid fa-fire" to S(0xf06d),
    "fa-solid fa-paper-plane" to S(0xf1d8),
    "fa-solid fa-qrcode" to S(0xf029),
    "fa-solid fa-language" to S(0xf1ab),
    "fa-solid fa-newspaper" to S(0xf1ea),
    "fa-solid fa-wallet" to S(0xf555),
    "fa-solid fa-utensils" to S(0xf2e7),
    "fa-solid fa-mug-hot" to S(0xf7b6),
    "fa-solid fa-shirt" to S(0xf553),
    "fa-solid fa-headphones" to S(0xf025),
    "fa-solid fa-microphone" to S(0xf130),
    "fa-solid fa-tv" to S(0xf26c),
    "fa-solid fa-robot" to S(0xf544),
    "fa-solid fa-brain" to S(0xf5dc),
    "fa-solid fa-dumbbell" to S(0xf44b),
    "fa-solid fa-paw" to S(0xf1b0),
    "fa-solid fa-leaf" to S(0xf06c),
    "fa-solid fa-cloud" to S(0xf0c2),
    "fa-solid fa-umbrella" to S(0xf0e9),
    "fa-solid fa-basket-shopping" to S(0xf291),
    "fa-solid fa-fingerprint" to S(0xf577),
    "fa-solid fa-key" to S(0xf084),
    "fa-solid fa-link" to S(0xf0c1),
    "fa-solid fa-share-nodes" to S(0xf1e0),
    "fa-brands fa-spotify" to B(0xf1bc),
    "fa-brands fa-twitter" to B(0xf099),
    "fa-brands fa-instagram" to B(0xf16d),
    "fa-brands fa-facebook" to B(0xf09a),
    "fa-brands fa-discord" to B(0xf392),
    "fa-brands fa-reddit" to B(0xf1a1),
    "fa-brands fa-amazon" to B(0xf270),
    "fa-brands fa-paypal" to B(0xf1ed),
    "fa-brands fa-linkedin" to B(0xf08c),
    "fa-brands fa-tiktok" to B(0xe07b),
    "fa-brands fa-snapchat" to B(0xf2ab),
    "fa-brands fa-steam" to B(0xf1b6),
    "fa-brands fa-twitch" to B(0xf1e8),
    )
}
